version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
      - .env-non-dev
  redis:
    image: redis:7
    container_name: redis_app
    command: --p 6379
    expose:
      - 6379
  app:
    build:
      context: .
    env_file:
      - server/.env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  #  rabbitmq:
  celery:
  flower: